### ISSUE TITLE
Display bug in latest BURP (2020.12.1)

### ISSUE THREAD

**Issue by martinbydefault** [synacktiv/burp-jq#2]
I just updated to latest BURP version and noticed this display bug:
![bug](https://user-images.githubusercontent.com/25038813/102636084-f59fe880-4132-11eb-9ada-32cc58c3a451.png)

**Comment by theblackturtle** [comment]
I have this bug too.

**Comment by aevy-syn** [comment]
Hi, this issue has been fixed and an update request was made to the BAppStore.
Thanks for the report!
